Wavefront Opentracing SDK Ruby
wavefrontHQ/wavefront-opentracing-sdk-ruby pull request #1
Opened 2019-02-08 22:42 UTC by gangadharaswamy

Wavefront Opentracing SDK Ruby tested on console reporter. Receiving data as below:

`"test_op" source="unknown" traceId=080c6a6c-a3f8-45a2-a24f-402753b3fec5 spanId=080c6a6c-a3f8-45a2-a24f-402753b3fec5 "key1"="val1" "key1"="val2" "application"="app" "service"="service" "cluster"="us-west-1" "shard"="primary" "custom_k"="custom_v" 1549663388000 0`

Testing is performed using MiniTest gem.
Code coverage is above 80%. Rake test files are added.

2019-02-20 10:04 UTC, yogeshprasad requested changes

2019-02-20 10:04 UTC, yogeshprasad commented on lib/wavefrontopentracing/propagation/propagator.rb
> +      # @param span_context [SpanContext]: The span context to serialize
Follow the YARD guideline for comments (Check all the files)
https://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md 
and this as well

https://github.com/rubocop-hq/ruby-style-guide

2019-02-20 10:04 UTC, yogeshprasad commented on lib/wavefrontopentracing/reporting/composite.rb
> +      reporter
return total_count

2019-02-20 10:04 UTC, yogeshprasad commented on util/utils.rb
> +
Please remove all tier one SDK files.

2019-02-20 10:04 UTC, yogeshprasad commented on lib/wavefrontopentracing/propagation/textmap.rb
> +          baggage.merge!(key[BAGGAGE_PREFIX.length..-1] => val)
please check this.

2019-03-08 06:39 UTC, yogeshprasad requested changes
some cosmetic changes,
Otherwise LGTM

2019-03-08 06:39 UTC, yogeshprasad commented on lib/wavefrontopentracing/propagation/registry.rb
> +      # @param format [OpenTracing::FORMAT] : Format a propagator
: can be removed

2019-03-08 06:39 UTC, yogeshprasad commented on lib/wavefrontopentracing/propagation/registry.rb
> +      # @param propagator [Propagator] : Propagator to be registered.
: can be removed

2019-03-08 06:39 UTC, yogeshprasad commented on wavefront-opentracing-sdk-ruby.gemspec
> +  spec.authors = ['wavefront-opentracing-sdk']
please update valid authors

2019-03-08 06:39 UTC, yogeshprasad commented on test/reporter_test.rb
> +    proxy_host = '10.192.167.61'
remove IP

2019-03-08 06:39 UTC, yogeshprasad commented on test/reporter_test.rb
> +                      'https://nimba.wavefront.com',
remove the API key and cluster name

2019-03-08 06:39 UTC, yogeshprasad commented on Gemfile.lock
> +PATH
please delete this file

2019-03-29 15:38 UTC, sushantdewan123 requested changes

2019-03-29 15:38 UTC, sushantdewan123 commented on .travis.yml
> +#  - gem install wavefront-client
please cleanup (delete) stale code instead of commenting out.

2019-03-29 15:38 UTC, sushantdewan123 commented on README.md
> +# default values: metrics_port = 2878, distribution_port = 40000, tracing_port = 30000
change distribution port to 2878

2019-03-29 15:38 UTC, sushantdewan123 commented on README.md
> +# default values: metrics_port = 2878, distribution_port = 40000, tracing_port = 30000
We recently switched from 40,000 to 2878

2019-03-29 15:38 UTC, sushantdewan123 commented on README.md
> +# wavefront_sender = Wavefront::WavefrontProxyClient.new(<proxy_host_ip>, metrics_port, distribution_port, tracing_port)
why is this commented out?

2019-03-29 15:38 UTC, sushantdewan123 commented on test/reporter_test.rb
> +                                   cluster: "virunga",
dont put virunga in here
please put 
us-west-2 as an example

2019-03-29 15:38 UTC, sushantdewan123 commented on test/reporter_test.rb
> +                                   shard: "shopping-shard",
use primary as an example for shard value

2019-03-29 15:38 UTC, sushantdewan123 commented on wavefront-opentracing-sdk-ruby.gemspec
> +  spec.email = ['gangadhar@vmware.com']
use the email address I had mentioned earlier

2019-03-29 16:28 UTC, gangadharaswamy commented on .travis.yml
> +#  - gem install wavefront-client
`wavefront-client` is for tier-1 SDK gem. For time-being it was commented. Will uncomment and check-in.

2019-03-29 16:30 UTC, gangadharaswamy commented on README.md
> +# wavefront_sender = Wavefront::WavefrontProxyClient.new(<proxy_host_ip>, metrics_port, distribution_port, tracing_port)
By default, direct ingestion sample code is uncommented. As an option ingestion via proxy code is commented out.

2019-03-29 17:43 UTC, sushantdewan123 approved these changes

2019-03-29 17:43 UTC, merged